# Generated by Django 4.2.4 on 2023-10-13 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_articulo', models.CharField(max_length=20, verbose_name='Nombre articulo')),
                ('nombre_proveedor', models.CharField(max_length=20)),
                ('unidades', models.PositiveIntegerField()),
                ('costo_unitario', models.PositiveIntegerField()),
                ('costo_envio', models.PositiveIntegerField()),
                ('codigo_articulo', models.CharField(max_length=20, verbose_name='Codigo')),
                ('imagen_producto', models.ImageField(null=True, upload_to='iamgenes/', verbose_name='Imagen del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_importacion', models.PositiveIntegerField()),
                ('costo_envio', models.PositiveIntegerField()),
                ('cif', models.PositiveIntegerField()),
                ('tasa_aduana', models.PositiveIntegerField()),
                ('iva', models.PositiveIntegerField()),
                ('impuestos', models.PositiveIntegerField()),
                ('total_compra', models.PositiveIntegerField()),
                ('valor_dolares', models.PositiveIntegerField()),
                ('id_importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='importacionapp.importacion')),
            ],
        ),
    ]
